name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: 18
          
    - name: install required tools
      run: cargo install wasm-pack
          
    - name: build wasm
      run: npm run build
      
    - name: install dependencies for nodejs
      run: npm i
      
    - name: Run tests
      run: npm run start
